config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  root 'posts#feed'

  match 'faq', to: 'pages#faq', via: :get
  match 'feed', to: 'posts#feed', via: :get
  match 'rss', to: 'posts#rss', via: :get
  match 'cloud_tags', to: 'posts#cloud_tags', via: :get

  Blog::Application.routes.draw do
    get 'tags/:tag', to: 'posts#feed', as: :tag
    resources :posts
  end

  match '404', to: 'errors#error_404', via: [ :get, :post, :patch, :delete ], code: 404
  match '500', to: 'errors#error_500', via: [ :get, :post, :patch, :delete ], code: 500

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, :content, :user_id, presence: true

  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable,
         :trackable,
         :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def error_404
    @error_code = 404
    render status: 404, layout: 'error'
  end

  def error_500
    @error_code = 500
    render status: 500, layout: 'error'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:feed, :show, :cloud_tags, :rss]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 7)
  end

  def feed
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 7)
    else
      @posts = Post.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 7)
    end
  end

  def rss
    respond_to do |format|
      format.html { }
      format.atom { @posts = Post.order(created_at: :desc).limit(14) }
      format.rss { @posts = Post.order(created_at: :desc).limit(14) }
    end
  end

  def cloud_tags
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Запись успешно создана.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Запись была успешно обновлена.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Запись была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def opengraph_config(page_title)
    { og_type: "website",
      og_title: page_title,
      og_description: "Dipiash. Блог о веб разработке и нетолько.",
      og_url: request.original_url
    }
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def create_preview(post_content)
    index = post_content =~ /&lt;truncate_text&gt;/ || post_content.length
    post_content[0,index]
  end

  def remove_truncate_text(post_content)
    post_content.gsub!("&lt;truncate_text&gt;", "") || post_content
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    - og = opengraph_config("Dipiash #{yield(:title)}")
    meta property="twitter:card" content="product"
    meta property="twitter:site" content="@dipiash"
    meta property="twitter:title" content="#{og[:og_title]}"
    meta property="twitter:description" content="#{og[:og_description]}"
    meta property="twitter:creator" content="@dipiash"

    meta property="og:type" content="#{og[:og_type]}"
    meta property="og:title" content="#{og[:og_title]}"
    meta property="og:description" content="#{og[:og_description]}"
    meta property="og:url" content="#{og[:og_url]}"

    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all'
    = javascript_include_tag 'application'
    = disqus_init
    = csrf_meta_tags

    title = "Dipiash #{yield(:title)}"
  body
    .wrapper
      = render 'pages/nav'
      main.container
        .col.s12
          = yield
      = render 'pages/footer'

    javascript:
      $(document).ready(function(){
        function selected_nav_item() {
          var path = window.location.pathname;
          $(document).find('a[href="' + path + '"]').parent().addClass('nav_items__item--selected')
        }

        selected_nav_item();
      });

app/views/layouts/error.html.slim
doctype html
html
  head
    = stylesheet_link_tag 'errors', media: 'all'
    = csrf_meta_tags

    title = "Dipiash #{yield(:title)}"
  body
    .container.white.z-depth-1 style=("text-align: center;")
      .error
        .error__code = "#{@error_code}"
        .error__message
          = yield
        .error__links
          p
            = "Вы можете вернуться на главную \
              #{link_to "страницу", root_path}".html_safe
            - if request.referer
              = ", или на предыдущую \
                #{link_to "страницу", URI(request.referer).path}.".html_safe
            - else
              = "."

app/views/pages/_footer.html.slim
footer.page-footer.white.z-depth-1.grey-text.lighten-1
  = "Копирование метериалов разрешается с указанием ссылки на оригинал. © 2015 Dipiash"

app/views/pages/_nav.html.slim
header.nav.row.z-depth-1
  .s12
    .logo.b_clearfix
      .logo__title Dipiash
      .logo__about Lorem ipsum dolor...
    ul.nav_items
      li.nav_items__item
        = link_to 'Лента новостей', root_path
      li.nav_items__item
        = link_to 'Облако тэгов', cloud_tags_path
      li.nav_items__item
        = link_to 'FAQ', faq_path
      - if user_signed_in?
        li.nav_items__item
          = link_to 'Записи', posts_path
        li.nav_items__item
          = link_to 'Выход', destroy_user_session_path, :method => :delete

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/contacts.html.slim
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/faq.html.slim
- title '| FAQ'

ul.collapsible data-collapsible="expandable"
  li
    .collapsible-header.active.light-blue-text.text-darken-1
      i.material-icons> filter_1
      | Кратко о себе
    .collapsible-body
      p
        | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo autem, voluptates rem. Odit quia a unde, voluptates tempore ad dolorum similique, sapiente eos hic illo laudantium libero voluptatibus, sit. Officia.
  li
    .collapsible-header.light-blue-text.text-darken-1
      i.material-icons> filter_2
      | Зачем мне блог
    .collapsible-body
      p
        |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro nisi vel reiciendis impedit optio. Fuga non ullam illum, adipisci, vitae blanditiis dignissimos veritatis! Neque aut deleniti distinctio animi iste. Vel!
  li
    .collapsible-header.light-blue-text.text-darken-1
      i.material-icons> filter_3
      | О чем я буду писать
    .collapsible-body
      p
        |  Lorem ipsum dolor sit amet, consectetur adipisicing elit. A amet, ratione saepe beatae ducimus voluptas est, asperiores quisquam minima veniam minus placeat eius libero cum magni voluptates consequatur obcaecati cupiditate.
  li
    .collapsible-header.light-blue-text.text-darken-1
      i.material-icons> filter_4
      | Начем написан блог
    .collapsible-body
      p
        = 'На Ruby on Rails. Для оформления пользовательског интерфейса использован фреймворк Materialize.'
  li
    .collapsible-header.light-blue-text.text-darken-1
      i.material-icons> filter_5
      | Для агрегаторов
    .collapsible-body
      p
        = "RSS: #{link_to 'ссылка', "#{rss_path}.rss", target: 'blank'}".html_safe
        br
        = "ATOM: #{link_to 'ссылка', "#{rss_path}.atom", target: 'blank'}".html_safe
  li
    .collapsible-header.light-blue-text.text-darken-1
      i.material-icons> filter_5
      | Github
    .collapsible-body
      p
        = 'GitHub: '
        a href='https://github.com/dipiash/blog' target='blank' dipiash


javascript:
  $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/links.html.erb
<h1>Pages#links</h1>
<p>Find me in app/views/pages/links.html.erb</p>

app/views/posts/_disqus.html.slim
#disqus_thread
javascript:
  var disqus_shortname = 'blogtestdipiash';
  var disqus_identifier = "#{@post.id}";
  var disqus_title = "#{@post.title}";
  var disqus_url = "#{request.original_url}";

  (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
noscript
  | Please enable JavaScript to view the
  a href="https://disqus.com/?ref_noscript" rel="nofollow"  comments powered by Disqus.

app/views/posts/_form.html.slim
= javascript_include_tag 'ckeditor/ckeditor.js'
= form_for(@post) do |f|
  - if @post.errors.any?
    div#error_explanation
      h5= "#{@post.errors.count} #{t(:errors, count: @post.errors.count)} обнаружено при создании записи:"
      ul.red-text.text-lighten-1
        - @post.errors.full_messages.each do |message|
          li= message

  .field
    = f.label :title, 'Название'
    br
    = f.text_field :title

  .field
    = f.label :content, 'Текст записи'
    br
    = f.cktext_area :content, :input_html => {:cols => 10, :rows => 40}, :toolbar => 'Full'

  .field
    = f.label :tag_list, 'Тэги (разделитель: запятая)'
    = f.text_field :tag_list

  .actions style=('margin-top: 10px;')
    = f.submit 'Подтвердить', class: 'btn'

app/views/posts/cloud_tags.html.slim
- title "| Облако тэгов"

article.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 10px;")
  h3 Облако тэгов
  p#tag_cloud
    - tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class

app/views/posts/edit.html.slim
- title '| Редактировать запись'
.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 20px;") data-no-turbolink=""
  h1 Редактировать запись

  = render 'form'

  .actions style=('margin-top: 10px;')
    = link_to 'Показать ', @post
    '|
    = link_to 'Назад', posts_path

app/views/posts/feed.html.slim
- title '| Новости'
.row
  - if @posts.length == 0
    article.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 10px; text-align: center;")
      p Ничего не найдено. Нет записей.
  - else
    - @posts.each do |post| %
      article.card.whith.z-depth-1
        .card-content
          h5.card-title.light-blue-text.text-darken-1
            = link_to "#{post.title.html_safe}", post
          p = "#{create_preview(post.content)}...".html_safe
          p
            span.grey-text.lighten-1 = "Теги: "
            = "#{post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}".html_safe
        .card-action.grey-text.lighten-1
          time(datetime="#{post.created_at.to_s(:db)}")= "Дата публикации: #{post.created_at.to_s(:db)}"
          = link_to "Читать полностью", post

  = will_paginate @posts, renderer: MaterializePagination::Rails

app/views/posts/index.html.slim
- title '| Список записей'
.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 20px;")
  h1 Список записей
  p#notice= notice
  = link_to 'Создать новую запись', new_post_path, class: 'btn'

  = will_paginate @posts, renderer: MaterializePagination::Rails
  table
    thead
      tr
        th Название
        th Текст записи
        th Время создания
        th Показать
        th Редактировать
        th Удалить
    tbody
      -@posts.each do |post|
        tr
          td = post.title.html_safe
          td = post.content.html_safe
          td = "#{time_ago_in_words(post.created_at)} назад"
          td = link_to 'Показать', post
          td = link_to 'Редактировать', edit_post_path(post)
          td = link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить запись?' }

  = will_paginate renderer: MaterializePagination::Rails

app/views/posts/new.html.slim
- title '| Новая запись'
.col.s12.z-depth-1.white data-no-turbolink="" style=("padding: 30px;")
  h1 Новая запись
  = render 'form'

  .actions style=('margin-top: 10px;')
    = link_to 'Назад', posts_path

app/views/posts/rss.html.slim
- title '| Агрегатор'
article.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 10px;")
  h3 Агрегатор
  p
    = link_to 'RSS', "#{rss_path}.rss"
    br
    = link_to 'Atom', "#{rss_path}.atom"

app/views/posts/show.html.slim
- title "| #{@post.title}"

article.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 10px;")
  h3 = @post.title
  hr
  p = "#{remove_truncate_text(@post.content)}".html_safe
  p
    span.grey-text.lighten-1 = "Теги: "
    = "#{@post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}".html_safe
    br
    time.grey-text.lighten-1(datetime="#{@post.created_at.to_s(:db)}")= "Дата публикации: #{@post.created_at.to_s(:db)}"

  - if user_signed_in?
    = link_to 'Редактировать ', edit_post_path(@post)
    '|
    = link_to 'Назад', posts_path
article.col.s12.z-depth-1.white style=("padding: 30px; margin-bottom: 20px;")
  = render 'disqus'